version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:3.6
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  app:
    build: ./
    working_dir: /northwind
    volumes:
      - ./:/northwind
      - ~/.m2:/root/.m2
    ports:
      - 8081:8081
    command: mvn clean spring-boot:run
    depends_on:
      - mongodb
