version: '3.7'
services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017

  northwind:
    container_name: northwind
    build: ./
    working_dir: /northwind
    volumes:
      - ./:/northwind
      - ~/.m2:/root/.m2
    ports:
      - 8088:8088
    command: bash -c "./mgodatagen --uri=mongodb://mongo:27017 -f db_data_config.json && mvn clean spring-boot:run"
    depends_on:
      - mongo

